spring:
  application:
    name: movie-details-server
  datasource:
    url: jdbc:mysql://localhost:3306/movieticketbooking
    password: 
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
      max-file-size: 200MB
    
server:
  port: 8888
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
